export const COURSE_ID = 'courseId'
export const DEPARTMENT_ID = 'departmentId'
export const PROGRAM_ID = 'programId'
export const SEMESTER_ID = 'semesterId'
export const SPECIALIZATION_ID = 'specializationId'
export const USER_ID = 'userId'
export const REVIEW_ID = 'reviewId'
