import {
	TPayloadDepartments,
	TPayloadEducationLevels,
	TPayloadGrades,
	TPayloadPrograms,
	TPayloadSemesters,
	TPayloadSpecializations,
	TPayloadSubjectAreas,
	TPayloadCoursesDataStatic,
} from '@globals/types'

export const departments: TPayloadDepartments = {
	CS: {
		departmentId: 'CS',
		name: 'Computer Science',
		url: 'https://www.scs.gatech.edu/',
	},
	CSE: {
		departmentId: 'CSE',
		name: 'Computational Science and Engineering',
		url: 'https://www.cse.gatech.edu/',
	},
	ECE: {
		departmentId: 'ECE',
		name: 'Electrical and Computer Engineering',
		url: 'https://ece.gatech.edu/',
	},
	INTA: {
		departmentId: 'INTA',
		name: 'International Affairs',
		url: 'https://inta.gatech.edu/',
	},
	ISYE: {
		departmentId: 'ISYE',
		name: 'Industrial and Systems Engineering',
		url: 'https://isye.gatech.edu/',
	},
	MGT: {
		departmentId: 'MGT',
		name: 'Management',
		url: 'https://www.scheller.gatech.edu/',
	},
	PUBP: {
		departmentId: 'PUBP',
		name: 'Public Policy',
		url: 'https://spp.gatech.edu/',
	},
}

export const programs: TPayloadPrograms = {
	a: {
		programId: 'a',
		name: 'Analytics',
		url: 'https://pe.gatech.edu/degrees/analytics',
	},
	cs: {
		programId: 'cs',
		name: 'Computer Science',
		url: 'https://pe.gatech.edu/degrees/computer-science',
	},
	cy: {
		programId: 'cy',
		name: 'Cybersecurity',
		url: 'https://pe.gatech.edu/degrees/cybersecurity',
	},
}

export const semesters: TPayloadSemesters = {
	sp: { semesterId: 'sp', term: 1, name: 'Spring' },
	sm: { semesterId: 'sm', term: 2, name: 'Summer' },
	fa: { semesterId: 'fa', term: 3, name: 'Fall' },
}

export const specializations: TPayloadSpecializations = {
	'a:at': {
		specializationId: 'a:at',
		name: 'Analytical Tools',
		programId: 'a',
	},
	'a:ba': {
		specializationId: 'a:ba',
		name: 'Business Analytics',
		programId: 'a',
	},
	'a:cda': {
		specializationId: 'a:cda',
		name: 'Computational Data Analytics',
		programId: 'a',
	},
	'cs:cpr': {
		specializationId: 'cs:cpr',
		name: 'Computational Perception and Robotics',
		programId: 'cs',
	},
	'cs:cs': {
		specializationId: 'cs:cs',
		name: 'Computing Systems',
		programId: 'cs',
	},
	'cs:ii': {
		specializationId: 'cs:ii',
		name: 'Interactive Intelligence',
		programId: 'cs',
	},
	'cs:ml': {
		specializationId: 'cs:ml',
		name: 'Machine Learning',
		programId: 'cs',
	},
	'cy:es': {
		specializationId: 'cy:es',
		name: 'Energy Systems',
		programId: 'cy',
	},
	'cy:is': {
		specializationId: 'cy:is',
		name: 'Information Security',
		programId: 'cy',
	},
	'cy:pol': { specializationId: 'cy:pol', name: 'Policy', programId: 'cy' },
}

export const educationLevels: TPayloadEducationLevels = {
	bach: { educationLevelId: 'bach', name: 'Bachelor' },
	mast: { educationLevelId: 'mast', name: 'Master' },
	phd: { educationLevelId: 'phd', name: 'Doctorate (PhD)' },
}

export const subjectAreas: TPayloadSubjectAreas = {
	act: { subjectAreaId: 'act', name: 'Actuarial Science' },
	bus: {
		subjectAreaId: 'bus',
		name: 'Business - Other/General (Accounting, etc.)',
	},
	cs: { subjectAreaId: 'cs', name: 'Computer Science' },
	econ: { subjectAreaId: 'econ', name: 'Economics' },
	engrElec: { subjectAreaId: 'engrElec', name: 'Electrical Engineering' },
	engrComp: { subjectAreaId: 'engrComp', name: 'Computer Engineering' },
	engrInd: { subjectAreaId: 'engrInd', name: 'Industrial Engineering' },
	engrOther: { subjectAreaId: 'engrOther', name: 'Other Engineering' },
	fin: { subjectAreaId: 'fin', name: 'Finance' },
	hlt: {
		subjectAreaId: 'hlt',
		name: 'Health or Healthcare-Related (PA, Dentistry, etc.)',
	},
	human: { subjectAreaId: 'human', name: 'Humanities' },
	it: { subjectAreaId: 'it', name: 'Information Technology' },
	law: { subjectAreaId: 'law', name: 'Law/Legal' },
	libArts: { subjectAreaId: 'libArts', name: 'Liberal Arts' },
	med: { subjectAreaId: 'med', name: 'Medicine or Premed' },
	mis: { subjectAreaId: 'mis', name: 'Management Information Systems' },
	math: { subjectAreaId: 'math', name: 'Mathematics' },
	natSci: {
		subjectAreaId: 'natSci',
		name: 'Natural Sciences (Biology, Chemistry, etc.)',
	},
	stats: { subjectAreaId: 'stats', name: 'Statistics' },
	or: { subjectAreaId: 'or', name: 'Operations Research' },
	phil: { subjectAreaId: 'phil', name: 'Philosophy' },
	phys: { subjectAreaId: 'phys', name: 'Physics' },
	zzOther: { subjectAreaId: 'zzOther', name: 'Other / Not Listed' },
}

export const grades: TPayloadGrades = {
	unk: { gradeId: 'unk', name: 'Prefer not to say' },
	w: { gradeId: 'w', name: 'W (Withdrawal)' },
	f: { gradeId: 'f', name: 'F' },
	d: { gradeId: 'd', name: 'D' },
	c: { gradeId: 'c', name: 'C' },
	b: { gradeId: 'b', name: 'B' },
	a: { gradeId: 'a', name: 'A' },
}

export const coursesDataStatic: TPayloadCoursesDataStatic = {
	'CS-6035': {
		courseId: 'CS-6035',
		name: 'Introduction to Information Security',
		departmentId: 'CS',
		courseNumber: '6035',
		url: 'https://omscs.gatech.edu/cs-6035-introduction-to-information-security',
		aliases: ['IIS'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6150': {
		courseId: 'CS-6150',
		name: 'Computing for Good',
		departmentId: 'CS',
		courseNumber: '6150',
		url: 'https://omscs.gatech.edu/cs-6150-computing-good',
		aliases: [],
		isDeprecated: false,
		isFoundational: false,
	},
	'CS-6200': {
		courseId: 'CS-6200',
		name: 'Graduate Introduction to Operating Systems',
		departmentId: 'CS',
		courseNumber: '6200',
		url: 'https://omscs.gatech.edu/cs-6200-introduction-operating-systems',
		aliases: ['GIOS', 'IOS'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6210': {
		courseId: 'CS-6210',
		name: 'Advanced Operating Systems',
		departmentId: 'CS',
		courseNumber: '6210',
		url: 'https://omscs.gatech.edu/cs-6210-advanced-operating-systems',
		aliases: ['AOS'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6211': {
		courseId: 'CS-6211',
		name: 'System Design for Cloud Computing',
		departmentId: 'CS',
		courseNumber: '6211',
		url: 'https://omscs.gatech.edu/cs-8803-o12-systems-issues-cloud-computing',
		aliases: ['SICC', 'SDCC'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6238': {
		courseId: 'CS-6238',
		name: 'Secure Computer Systems',
		departmentId: 'CS',
		courseNumber: '6238',
		url: 'https://omscs.gatech.edu/cs-6238-secure-computer-systems',
		aliases: ['SCS'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6250': {
		courseId: 'CS-6250',
		name: 'Computer Networks',
		departmentId: 'CS',
		courseNumber: '6250',
		url: 'https://omscs.gatech.edu/cs-6250-computer-networks',
		aliases: ['CN'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6260': {
		courseId: 'CS-6260',
		name: 'Applied Cryptography',
		departmentId: 'CS',
		courseNumber: '6260',
		url: 'https://omscs.gatech.edu/cs-6260-applied-cryptography',
		aliases: ['AC'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6262': {
		courseId: 'CS-6262',
		name: 'Network Security',
		departmentId: 'CS',
		courseNumber: '6262',
		url: 'https://omscs.gatech.edu/cs-6262-network-security',
		aliases: ['NS'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6263': {
		courseId: 'CS-6263',
		name: 'Intro to Cyber-Physical Systems Security',
		departmentId: 'CS',
		courseNumber: '6263',
		url: 'https://omscs.gatech.edu/cs-8803-special-topics-cyber-physical-systems',
		aliases: ['CPSS'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6264': {
		courseId: 'CS-6264',
		name: 'Information Security Lab: System and Network Defenses',
		departmentId: 'CS',
		courseNumber: '6264',
		url: 'https://omscs.gatech.edu/cs-6264-information-security-lab-system-and-network-defenses',
		aliases: ['SND', 'ISND', 'ISLND'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6265': {
		courseId: 'CS-6265',
		name: 'Information Security Laboratory',
		departmentId: 'CS',
		courseNumber: '6265',
		url: 'https://omscs.gatech.edu/cs-6265-information-security-lab',
		aliases: ['ISL'],
		isDeprecated: false,
		isFoundational: false,
	},
	'CS-6266': {
		courseId: 'CS-6266',
		name: 'Information Security Practicum',
		departmentId: 'CS',
		courseNumber: '6266',
		url: null,
		aliases: [],
		isDeprecated: true,
		isFoundational: false,
	},
	'CS-6290': {
		courseId: 'CS-6290',
		name: 'High-Performance Computer Architecture',
		departmentId: 'CS',
		courseNumber: '6290',
		url: 'https://omscs.gatech.edu/cs-6290-high-performance-computer-architecture',
		aliases: ['HPCA'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6291': {
		courseId: 'CS-6291',
		name: 'Embedded Software Optimizations',
		departmentId: 'CS',
		courseNumber: '6291',
		url: 'https://omscs.gatech.edu/cs-6291-embedded-systems-optimization',
		aliases: ['ESO'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6300': {
		courseId: 'CS-6300',
		name: 'Software Development Process',
		departmentId: 'CS',
		courseNumber: '6300',
		url: 'https://omscs.gatech.edu/cs-6300-software-development-process',
		aliases: ['SDP'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6310': {
		courseId: 'CS-6310',
		name: 'Software Architecture and Design',
		departmentId: 'CS',
		courseNumber: '6310',
		url: 'https://omscs.gatech.edu/cs-6310-software-architecture-design',
		aliases: ['SAD'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6340': {
		courseId: 'CS-6340',
		name: 'Advanced Topics in Software Analysis and Testing',
		departmentId: 'CS',
		courseNumber: '6340',
		url: 'https://omscs.gatech.edu/cs-6340-software-analysis',
		aliases: ['SA', 'SAT'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6400': {
		courseId: 'CS-6400',
		name: 'Database Systems Concepts and Design',
		departmentId: 'CS',
		courseNumber: '6400',
		url: 'https://omscs.gatech.edu/cs-6400-database-systems-concepts-and-design',
		aliases: ['DBS', 'DBSD'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6440': {
		courseId: 'CS-6440',
		name: 'Introduction to Health Informatics',
		departmentId: 'CS',
		courseNumber: '6440',
		url: 'https://omscs.gatech.edu/cs-6440-intro-health-informatics',
		aliases: ['IHI'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6457': {
		courseId: 'CS-6457',
		name: 'Video Game Design and Programming',
		departmentId: 'CS',
		courseNumber: '6457',
		url: 'https://omscs.gatech.edu/cs-6457-video-game-design',
		aliases: ['VGD'],
		isDeprecated: false,
		isFoundational: false,
	},
	'CS-6460': {
		courseId: 'CS-6460',
		name: 'Educational Technology: Conceptual Foundations',
		departmentId: 'CS',
		courseNumber: '6460',
		url: 'https://omscs.gatech.edu/cs-6460-educational-technology',
		aliases: ['EdTech'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6465': {
		courseId: 'CS-6465',
		name: 'Computational Journalism',
		departmentId: 'CS',
		courseNumber: '6465',
		url: null,
		aliases: ['CJ'],
		isDeprecated: true,
		isFoundational: false,
	},
	'CS-6475': {
		courseId: 'CS-6475',
		name: 'Computational Photography',
		departmentId: 'CS',
		courseNumber: '6475',
		url: 'https://omscs.gatech.edu/cs-6475-computational-photography',
		aliases: ['CP'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6476': {
		courseId: 'CS-6476',
		name: 'Introduction to Computer Vision',
		departmentId: 'CS',
		courseNumber: '6476',
		url: 'https://omscs.gatech.edu/cs-6476-computer-vision',
		aliases: ['CV'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6515': {
		courseId: 'CS-6515',
		name: 'Introduction to Graduate Algorithms',
		departmentId: 'CS',
		courseNumber: '6515',
		url: 'https://omscs.gatech.edu/cs-6515-intro-graduate-algorithms',
		aliases: ['GA'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6601': {
		courseId: 'CS-6601',
		name: 'Artificial Intelligence',
		departmentId: 'CS',
		courseNumber: '6601',
		url: 'https://omscs.gatech.edu/cs-6601-artificial-intelligence',
		aliases: ['AI'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6603': {
		courseId: 'CS-6603',
		name: 'AI, Ethics, and Society',
		departmentId: 'CS',
		courseNumber: '6603',
		url: 'https://omscs.gatech.edu/cs-6603-ai-ethics-and-society',
		aliases: ['AIES', 'AI-Ethics'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6675': {
		courseId: 'CS-6675',
		name: 'Advanced Internet Computing Systems and Applications',
		departmentId: 'CS',
		courseNumber: '6675',
		url: 'https://omscs.gatech.edu/cs-6675-advanced-internet-systems-and-applications',
		aliases: ['AISA'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6726': {
		courseId: 'CS-6726',
		name: 'Privacy, Technology, Policy, and Law',
		departmentId: 'CS',
		courseNumber: '6726',
		url: null,
		aliases: [],
		isDeprecated: true,
		isFoundational: false,
	},
	'CS-6727': {
		courseId: 'CS-6727',
		name: 'Cyber Security Practicum',
		departmentId: 'CS',
		courseNumber: '6727',
		url: null,
		aliases: [],
		isDeprecated: true,
		isFoundational: false,
	},
	'CS-6747': {
		courseId: 'CS-6747',
		name: 'Advanced Topics in Malware Analysis',
		departmentId: 'CS',
		courseNumber: '6747',
		url: 'https://omscs.gatech.edu/cs-6747-advanced-malware-analysis',
		aliases: ['AMA', 'ATMA'],
		isDeprecated: false,
		isFoundational: false,
	},
	'CS-6750': {
		courseId: 'CS-6750',
		name: 'Human-Computer Interaction',
		departmentId: 'CS',
		courseNumber: '6750',
		url: 'https://omscs.gatech.edu/cs-6750-human-computer-interaction',
		aliases: ['HCI'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-6795': {
		courseId: 'CS-6795',
		name: 'Introduction to Cognitive Science',
		departmentId: 'CS',
		courseNumber: '6795',
		url: 'https://omscs.gatech.edu/cs-6795-introduction-cognitive-science',
		aliases: ['ICS'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-7210': {
		courseId: 'CS-7210',
		name: 'Distributed Computing',
		departmentId: 'CS',
		courseNumber: '7210',
		url: 'https://omscs.gatech.edu/cs-7210-distributed-computing',
		aliases: ['DC'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-7280': {
		courseId: 'CS-7280',
		name: 'Network Science: Methods and Applications',
		departmentId: 'CS',
		courseNumber: '7280',
		url: 'https://omscs.gatech.edu/cs-7280-network-science',
		aliases: ['NS'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-7450': {
		courseId: 'CS-7450',
		name: 'Information Visualization',
		departmentId: 'CS',
		courseNumber: '7450',
		url: null,
		aliases: ['IV'],
		isDeprecated: true,
		isFoundational: false,
	},
	'CS-7470': {
		courseId: 'CS-7470',
		name: 'Mobile and Ubiquitous Computing',
		departmentId: 'CS',
		courseNumber: '7470',
		url: 'https://omscs.gatech.edu/cs-7470-mobile-ubiquitous-computing',
		aliases: ['MUC'],
		isDeprecated: false,
		isFoundational: false,
	},
	'CS-7632': {
		courseId: 'CS-7632',
		name: 'Game Artificial Intelligence',
		departmentId: 'CS',
		courseNumber: '7632',
		url: 'https://omscs.gatech.edu/cs-7632-game-ai',
		aliases: ['GAI'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-7637': {
		courseId: 'CS-7637',
		name: 'Knowledge-Based Artificial Intelligence: Cognitive Systems',
		departmentId: 'CS',
		courseNumber: '7637',
		url: 'https://omscs.gatech.edu/cs-7637-knowledge-based-artificial-intelligence-cognitive-systems',
		aliases: ['KBAI'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-7638': {
		courseId: 'CS-7638',
		name: 'Artificial Intelligence Techniques for Robotics',
		departmentId: 'CS',
		courseNumber: '7638',
		url: 'https://omscs.gatech.edu/cs-7638-artificial-intelligence-robotics',
		aliases: ['AI4R', 'RAIT'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-7639': {
		courseId: 'CS-7639',
		name: 'Cyber Physical Design and Analysis',
		departmentId: 'CS',
		courseNumber: '7639',
		url: 'https://omscs.gatech.edu/cs-7639-cyber-physical-design-and-analysis',
		aliases: ['CPDA'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-7641': {
		courseId: 'CS-7641',
		name: 'Machine Learning',
		departmentId: 'CS',
		courseNumber: '7641',
		url: 'https://omscs.gatech.edu/cs-7641-machine-learning',
		aliases: ['ML'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-7642': {
		courseId: 'CS-7642',
		name: 'Reinforcement Learning and Decision Making',
		departmentId: 'CS',
		courseNumber: '7642',
		url: 'https://www.omscs.gatech.edu/cs-7642-reinforcement-learning',
		aliases: ['RL', 'RLDM'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-7643': {
		courseId: 'CS-7643',
		name: 'Deep Learning',
		departmentId: 'CS',
		courseNumber: '7643',
		url: 'https://omscs.gatech.edu/cs-7643-deep-learning',
		aliases: ['DL'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-7646': {
		courseId: 'CS-7646',
		name: 'Machine Learning for Trading',
		departmentId: 'CS',
		courseNumber: '7646',
		url: 'https://omscs.gatech.edu/cs-7646-machine-learning-trading',
		aliases: ['ML4T'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-7650': {
		courseId: 'CS-7650',
		name: 'Natural Language Processing',
		departmentId: 'CS',
		courseNumber: '7650',
		url: 'https://omscs.gatech.edu/cs-7650-natural-language-processing',
		aliases: ['NLP'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-8803-O04': {
		courseId: 'CS-8803-O04',
		name: 'Embedded Software',
		departmentId: 'CS',
		courseNumber: '8803-O04',
		url: null,
		aliases: [],
		isDeprecated: true,
		isFoundational: false,
	},
	'CS-8803-O05': {
		courseId: 'CS-8803-O05',
		name: 'Data Visualization for Health Informatics',
		departmentId: 'CS',
		courseNumber: '8803-O05',
		url: null,
		aliases: [],
		isDeprecated: true,
		isFoundational: false,
	},
	'CS-8803-O06': {
		courseId: 'CS-8803-O06',
		name: 'Biomedical Analytics',
		departmentId: 'CS',
		courseNumber: '8803-O06',
		url: null,
		aliases: [],
		isDeprecated: true,
		isFoundational: false,
	},
	'CS-8803-O08': {
		courseId: 'CS-8803-O08',
		name: 'Compilers: Theory and Practice',
		departmentId: 'CS',
		courseNumber: '8803-O08',
		url: 'https://omscs.gatech.edu/cs-8803-o08-compilers-theory-and-practice',
		aliases: [],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-8803-O12': {
		courseId: 'CS-8803-O12',
		name: 'Systems Issues in Cloud Computing',
		departmentId: 'CS',
		courseNumber: '8803-O12',
		url: 'https://omscs.gatech.edu/cs-8803-o12-systems-issues-cloud-computing',
		aliases: ['SICC', 'SDCC'],
		isDeprecated: true,
		isFoundational: true,
	},
	'CS-8803-O13': {
		courseId: 'CS-8803-O13',
		name: 'Quantum Computing',
		departmentId: 'CS',
		courseNumber: '8803-O13',
		url: 'https://omscs.gatech.edu/cs-8803-o13-quantum-computing',
		aliases: ['QC'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CS-8803-O15': {
		courseId: 'CS-8803-O15',
		name: 'Introduction to Computing Law',
		departmentId: 'CS',
		courseNumber: '8803-O15',
		url: 'https://omscs.gatech.edu/cs-8803-o15-computing-law',
		aliases: ['ICL', 'CL'],
		isDeprecated: false,
		isFoundational: false,
	},
	'CS-8803-O16': {
		courseId: 'CS-8803-O16',
		name: 'Digital Health Equity',
		departmentId: 'CS',
		courseNumber: '8803-O16',
		url: 'https://omscs.gatech.edu/cs-8803-o16-digital-health-equity',
		aliases: ['DHE'],
		isDeprecated: false,
		isFoundational: false,
	},
	'CS-8803-O17': {
		courseId: 'CS-8803-O17',
		name: 'Global Entrepreneurship',
		departmentId: 'CS',
		courseNumber: '8803-O17',
		url: 'https://omscs.gatech.edu/cs-8803-o17-global-entrepreneurship',
		aliases: ['GE'],
		isDeprecated: false,
		isFoundational: false,
	},
	'CS-8803-OC1': {
		courseId: 'CS-8803-OC1',
		name: 'Security Operations and Incidence Response',
		departmentId: 'CS',
		courseNumber: '8803-OC1',
		url: null,
		aliases: [],
		isDeprecated: false,
		isFoundational: false,
	},
	'CS-8813': {
		courseId: 'CS-8813',
		name: 'Malware Analysis and Defense',
		departmentId: 'CS',
		courseNumber: '8813',
		url: null,
		aliases: [],
		isDeprecated: false,
		isFoundational: false,
	},
	'CSE-6040': {
		courseId: 'CSE-6040',
		name: 'Computing for Data Analysis: Methods and Tools',
		departmentId: 'CSE',
		courseNumber: '6040',
		url: null,
		aliases: ['CDA'],
		isDeprecated: false,
		isFoundational: false,
	},
	'CSE-6140': {
		courseId: 'CSE-6140',
		name: 'Computational Science and Engineering Algorithms',
		departmentId: 'CSE',
		courseNumber: '6140',
		url: null,
		aliases: [],
		isDeprecated: false,
		isFoundational: false,
	},
	'CSE-6220': {
		courseId: 'CSE-6220',
		name: 'High Performance Computing',
		departmentId: 'CSE',
		courseNumber: '6220',
		url: 'https://omscs.gatech.edu/cse-6220-intro-hpc',
		aliases: ['HPC', 'IHPC'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CSE-6240': {
		courseId: 'CSE-6240',
		name: 'Web Search and Text Mining',
		departmentId: 'CSE',
		courseNumber: '6240',
		url: null,
		aliases: [],
		isDeprecated: false,
		isFoundational: false,
	},
	'CSE-6242': {
		courseId: 'CSE-6242',
		name: 'Data and Visual Analytics',
		departmentId: 'CSE',
		courseNumber: '6242',
		url: 'https://omscs.gatech.edu/cse-6242-data-visual-analytics',
		aliases: ['DVA'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CSE-6250': {
		courseId: 'CSE-6250',
		name: 'Big Data Analytics for Healthcare',
		departmentId: 'CSE',
		courseNumber: '6250',
		url: 'https://omscs.gatech.edu/cse-8803-special-topics-big-data-for-health-informatics',
		aliases: ['BD4H', 'BDHI'],
		isDeprecated: false,
		isFoundational: true,
	},
	'CSE-6742': {
		courseId: 'CSE-6742',
		name: 'Modeling, Simulation, and Military Gaming',
		departmentId: 'CSE',
		courseNumber: '6742',
		url: 'https://omscs.gatech.edu/cse-6742-modeling-simulation-and-military-gaming',
		aliases: ['MSMG'],
		isDeprecated: false,
		isFoundational: false,
	},
	'ECE-6150': {
		courseId: 'ECE-6150',
		name: 'Computational Aspects of Cyber Physical Systems',
		departmentId: 'ECE',
		courseNumber: '6150',
		url: null,
		aliases: [],
		isDeprecated: false,
		isFoundational: false,
	},
	'ECE-6266': {
		courseId: 'ECE-6266',
		name: 'Energy Systems Practicum',
		departmentId: 'ECE',
		courseNumber: '6266',
		url: null,
		aliases: [],
		isDeprecated: true,
		isFoundational: false,
	},
	'ECE-6320': {
		courseId: 'ECE-6320',
		name: 'Power Systems Control and Operation',
		departmentId: 'ECE',
		courseNumber: '6320',
		url: null,
		aliases: [],
		isDeprecated: false,
		isFoundational: false,
	},
	'ECE-6323': {
		courseId: 'ECE-6323',
		name: 'Power System Protection',
		departmentId: 'ECE',
		courseNumber: '6323',
		url: null,
		aliases: [],
		isDeprecated: false,
		isFoundational: false,
	},
	'ECE-8803a': {
		courseId: 'ECE-8803a',
		name: 'Computational Aspects of Cyber Physical Systems',
		departmentId: 'ECE',
		courseNumber: '8803a',
		url: null,
		aliases: [],
		isDeprecated: false,
		isFoundational: false,
	},
	'ECE-8803c': {
		courseId: 'ECE-8803c',
		name: 'Embedded Systems',
		departmentId: 'ECE',
		courseNumber: '8803c',
		url: null,
		aliases: [],
		isDeprecated: true,
		isFoundational: false,
	},
	'ECE-8803d': {
		courseId: 'ECE-8803d',
		name: 'Embedded Systems Security',
		departmentId: 'ECE',
		courseNumber: '8803d',
		url: null,
		aliases: [],
		isDeprecated: true,
		isFoundational: false,
	},
	'ECE-8803e': {
		courseId: 'ECE-8803e',
		name: 'Introduction to Cyber Physical Electric Energy Systems',
		departmentId: 'ECE',
		courseNumber: '8803e',
		url: null,
		aliases: [],
		isDeprecated: false,
		isFoundational: false,
	},
	'ECE-8803g': {
		courseId: 'ECE-8803g',
		name: 'Smart Grids',
		departmentId: 'ECE',
		courseNumber: '8803g',
		url: null,
		aliases: [],
		isDeprecated: false,
		isFoundational: false,
	},
	'ECE-8803h': {
		courseId: 'ECE-8803h',
		name: 'Software Vulnerabilities & Security',
		departmentId: 'ECE',
		courseNumber: '8803h',
		url: null,
		aliases: [],
		isDeprecated: true,
		isFoundational: false,
	},
	'ECE-8813': {
		courseId: 'ECE-8813',
		name: 'Introduction to Cyber Physical Systems Security',
		departmentId: 'ECE',
		courseNumber: '8813',
		url: null,
		aliases: [],
		isDeprecated: false,
		isFoundational: false,
	},
	'ECE-8823': {
		courseId: 'ECE-8823',
		name: 'Cyber Physical Design',
		departmentId: 'ECE',
		courseNumber: '8823',
		url: null,
		aliases: ['CPDA'],
		isDeprecated: false,
		isFoundational: false,
	},
	'ECE-8843': {
		courseId: 'ECE-8843',
		name: 'Side-Channels and Their Role in Cybersecurity',
		departmentId: 'ECE',
		courseNumber: '8843',
		url: 'https://omscs.gatech.edu/ece-8843-side-channels-and-their-role-cybersecurity',
		aliases: [],
		isDeprecated: false,
		isFoundational: false,
	},
	'ECE-8853': {
		courseId: 'ECE-8853',
		name: 'Introduction to Cyber Physical Electric Energy Systems',
		departmentId: 'ECE',
		courseNumber: '8853',
		url: null,
		aliases: [],
		isDeprecated: false,
		isFoundational: false,
	},
	'ECE-8863': {
		courseId: 'ECE-8863',
		name: 'Principles of Smart Electricity Grids',
		departmentId: 'ECE',
		courseNumber: '8863',
		url: null,
		aliases: [],
		isDeprecated: false,
		isFoundational: false,
	},
	'ECE-8873': {
		courseId: 'ECE-8873',
		name: 'Advanced Hardware Oriented Security and Trust',
		departmentId: 'ECE',
		courseNumber: '8873',
		url: null,
		aliases: [],
		isDeprecated: false,
		isFoundational: false,
	},
	'INTA-6014': {
		courseId: 'INTA-6014',
		name: 'Scenario Writing and Path Gaming',
		departmentId: 'INTA',
		courseNumber: '6014',
		url: null,
		aliases: [],
		isDeprecated: false,
		isFoundational: false,
	},
	'INTA-6103': {
		courseId: 'INTA-6103',
		name: 'International Security',
		departmentId: 'INTA',
		courseNumber: '6103',
		url: null,
		aliases: ['IS'],
		isDeprecated: false,
		isFoundational: false,
	},
	'INTA-6450': {
		courseId: 'INTA-6450',
		name: 'Data Analytics and Security',
		departmentId: 'INTA',
		courseNumber: '6450',
		url: 'https://omscs.gatech.edu/inta-6450-data-analytics-and-security',
		aliases: ['DAS'],
		isDeprecated: false,
		isFoundational: false,
	},
	'INTA-8803G': {
		courseId: 'INTA-8803G',
		name: 'Challenge of Terrorism in Democratic Societies',
		departmentId: 'INTA',
		courseNumber: '8803G',
		url: null,
		aliases: [],
		isDeprecated: false,
		isFoundational: false,
	},
	'ISYE-6402': {
		courseId: 'ISYE-6402',
		name: 'Time Series Analysis',
		departmentId: 'ISYE',
		courseNumber: '6402',
		url: 'https://omscs.gatech.edu/isye-6402-time-series-analysis',
		aliases: ['TSA'],
		isDeprecated: false,
		isFoundational: false,
	},
	'ISYE-6404': {
		courseId: 'ISYE-6404',
		name: 'Nonparametric Data Analysis',
		departmentId: 'ISYE',
		courseNumber: '6404',
		url: null,
		aliases: ['NDA'],
		isDeprecated: false,
		isFoundational: false,
	},
	'ISYE-6413': {
		courseId: 'ISYE-6413',
		name: 'Design and Analysis of Experiments',
		departmentId: 'ISYE',
		courseNumber: '6413',
		url: null,
		aliases: ['DAE'],
		isDeprecated: false,
		isFoundational: false,
	},
	'ISYE-6414': {
		courseId: 'ISYE-6414',
		name: 'Statistical Modeling and Regression Analysis',
		departmentId: 'ISYE',
		courseNumber: '6414',
		url: null,
		aliases: ['RA', 'SMRA'],
		isDeprecated: false,
		isFoundational: false,
	},
	'ISYE-6416': {
		courseId: 'ISYE-6416',
		name: 'Computational Statistics',
		departmentId: 'ISYE',
		courseNumber: '6416',
		url: null,
		aliases: ['CS'],
		isDeprecated: false,
		isFoundational: false,
	},
	'ISYE-6420': {
		courseId: 'ISYE-6420',
		name: 'Introduction to Theory and Practice of Bayesian Statistics',
		departmentId: 'ISYE',
		courseNumber: '6420',
		url: 'https://omscs.gatech.edu/isye-6420-bayesian-statistics',
		aliases: ['BS'],
		isDeprecated: false,
		isFoundational: true,
	},
	'ISYE-6501': {
		courseId: 'ISYE-6501',
		name: 'Introduction to Analytics Modeling',
		departmentId: 'ISYE',
		courseNumber: '6501',
		url: 'https://omscs.gatech.edu/isye-6501-intro-analytics-modeling',
		aliases: ['IAM'],
		isDeprecated: false,
		isFoundational: false,
	},
	'ISYE-6644': {
		courseId: 'ISYE-6644',
		name: 'Simulation and Modeling for Engineering and Science',
		departmentId: 'ISYE',
		courseNumber: '6644',
		url: 'https://omscs.gatech.edu/isye-6644-simulation-and-modeling-engineering-and-science',
		aliases: ['SM', 'SMES'],
		isDeprecated: false,
		isFoundational: false,
	},
	'ISYE-6650': {
		courseId: 'ISYE-6650',
		name: 'Probabilistic Models and Their Applications',
		departmentId: 'ISYE',
		courseNumber: '6650',
		url: null,
		aliases: ['PM'],
		isDeprecated: false,
		isFoundational: false,
	},
	'ISYE-6669': {
		courseId: 'ISYE-6669',
		name: 'Deterministic Optimization',
		departmentId: 'ISYE',
		courseNumber: '6669',
		url: null,
		aliases: ['DO'],
		isDeprecated: false,
		isFoundational: false,
	},
	'ISYE-6740': {
		courseId: 'ISYE-6740',
		name: 'Computational Data Analysis: Learning, Mining, and Computation',
		departmentId: 'ISYE',
		courseNumber: '6740',
		url: null,
		aliases: ['CDA'],
		isDeprecated: false,
		isFoundational: false,
	},
	'ISYE-7406': {
		courseId: 'ISYE-7406',
		name: 'Data Mining and Statistical Learning',
		departmentId: 'ISYE',
		courseNumber: '7406',
		url: null,
		aliases: ['DM', 'DMSL'],
		isDeprecated: false,
		isFoundational: false,
	},
	'ISYE-8803': {
		courseId: 'ISYE-8803',
		name: 'High-Dimensional Data Analytics',
		departmentId: 'ISYE',
		courseNumber: '8803',
		url: 'https://omscs.gatech.edu/isye-8803-topics-high-dimensional-data-analytics',
		aliases: ['HDDA'],
		isDeprecated: false,
		isFoundational: false,
	},
	'MGT-6203': {
		courseId: 'MGT-6203',
		name: 'Data Analytics in Business',
		departmentId: 'MGT',
		courseNumber: '6203',
		url: null,
		aliases: ['DAB'],
		isDeprecated: false,
		isFoundational: false,
	},
	'MGT-6311': {
		courseId: 'MGT-6311',
		name: 'Digital Marketing',
		departmentId: 'MGT',
		courseNumber: '6311',
		url: 'https://omscs.gatech.edu/mgt-6311-digital-marketing',
		aliases: ['DM'],
		isDeprecated: false,
		isFoundational: false,
	},
	'MGT-6727': {
		courseId: 'MGT-6727',
		name: 'Privacy for Professionals',
		departmentId: 'MGT',
		courseNumber: '6727',
		url: null,
		aliases: ['PP'],
		isDeprecated: false,
		isFoundational: false,
	},
	'MGT-6748': {
		courseId: 'MGT-6748',
		name: 'Applied Analytics Practicum',
		departmentId: 'MGT',
		courseNumber: '6748',
		url: null,
		aliases: ['AAP'],
		isDeprecated: false,
		isFoundational: false,
	},
	'MGT-8803': {
		courseId: 'MGT-8803',
		name: 'Business Fundamentals for Analytics',
		departmentId: 'MGT',
		courseNumber: '8803',
		url: null,
		aliases: ['BFA'],
		isDeprecated: false,
		isFoundational: true,
	},
	'MGT-8813': {
		courseId: 'MGT-8813',
		name: 'Financial Modeling',
		departmentId: 'MGT',
		courseNumber: '8813',
		url: null,
		aliases: ['FM'],
		isDeprecated: false,
		isFoundational: false,
	},
	'MGT-8823': {
		courseId: 'MGT-8823',
		name: 'Data Analytics and Continuous Improvement',
		departmentId: 'MGT',
		courseNumber: '8823',
		url: null,
		aliases: ['DACI'],
		isDeprecated: false,
		isFoundational: false,
	},
	'PUBP-6111': {
		courseId: 'PUBP-6111',
		name: 'Internet and Public Policy',
		departmentId: 'PUBP',
		courseNumber: '6111',
		url: null,
		aliases: ['IPP'],
		isDeprecated: false,
		isFoundational: false,
	},
	'PUBP-6266': {
		courseId: 'PUBP-6266',
		name: 'Policy Practicum',
		departmentId: 'PUBP',
		courseNumber: '6266',
		url: null,
		aliases: ['PP'],
		isDeprecated: true,
		isFoundational: false,
	},
	'PUBP-6501': {
		courseId: 'PUBP-6501',
		name: 'Information Policy and Management',
		departmentId: 'PUBP',
		courseNumber: '6501',
		url: null,
		aliases: ['IPM'],
		isDeprecated: false,
		isFoundational: false,
	},
	'PUBP-6502': {
		courseId: 'PUBP-6502',
		name: 'Information and Communications Technology Policy',
		departmentId: 'PUBP',
		courseNumber: '6502',
		url: null,
		aliases: ['ICTP', 'ICP'],
		isDeprecated: false,
		isFoundational: false,
	},
	'PUBP-6725': {
		courseId: 'PUBP-6725',
		name: 'Information Security Policies and Strategies',
		departmentId: 'PUBP',
		courseNumber: '6725',
		url: 'https://omscs.gatech.edu/pubp-6725-information-security-policies',
		aliases: ['ISP', 'ISPS'],
		isDeprecated: false,
		isFoundational: false,
	},
	/* IGNORE -- ambiguous departmentId */
	// 'VIP-6600': {
	// 	courseId: 'VIP-6600',
	// 	departmentId: 'VIP',
	// 	courseNumber: '6600',
	// 	name: 'Vertically Integrated Projects',
	// 	aliases: ['VIP'],
	// 	url: 'https://www.vip.gatech.edu/',
	// 	isFoundational: true,
	// 	isDeprecated: true,
	// },
}
