create table public.review (
  id bigint generated by default as identity not null,
  "reviewId" text not null,
  "courseId" text not null,
  "year" numeric not null,
  "semesterId" text not null,
  "isLegacy" boolean not null default false,
  "reviewerId" text null,
  "isGTVerifiedReviewer" boolean not null default false,
  created numeric not null,
  modified numeric null,
  workload numeric not null,
  difficulty numeric not null,
  overall numeric not null,
  upvotes numeric not null default '0'::numeric,
  downvotes numeric not null default '0'::numeric,
  body text not null default '""'::text,
  constraint review_pkey primary key (id)
) tablespace pg_default;

create index if not exists "review_reviewId_idx" on public.review using btree ("reviewId") tablespace pg_default;

create index if not exists "review_courseId_year_semesterId_idx" on public.review using btree ("courseId", "year", "semesterId") tablespace pg_default;

create index if not exists "review_reviewerId_idx" on public.review using btree ("reviewerId") tablespace pg_default;

create index if not exists "review_courseId_year_semesterId_reviewerId_idx" on public.review using btree ("courseId", "year", "semesterId", "reviewerId") tablespace pg_default;

create index if not exists "review_year_semesterId_idx" on public.review using btree ("year", "semesterId") tablespace pg_default;

create index if not exists "review_year_semesterId_courseId_idx" on public.review using btree ("year", "semesterId", "courseId") tablespace pg_default;

create index if not exists "review_year_idx" on public.review using btree ("year") tablespace pg_default;

create index if not exists "review_semesterId_idx" on public.review using btree ("semesterId") tablespace pg_default;

create index if not exists "review_courseId_idx" on public.review using btree ("courseId") tablespace pg_default;
