
name: 'Build Sitemap'

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: 'Build and Create Sitemap'
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn build
      - run: yarn build-sitemap
